### ISSUE TITLE
Error handling fails on OSX 10.11 (ruby 2.0.0)

### ISSUE THREAD

**Issue by benh57** [andersonvom/adp-downloader#3]
Looks like this works fine with Ruby 2.4.0, but the default ruby on OS X El Capitan throws this when it tries to throw any error. Otherwise, works fine!

Maybe 10.12 has a later default ruby? I'm still on El Cap since my company still hasn't yet 'certified' Sierra.

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tempfile.rb:128:in `initialize': wrong number of arguments (0 for 1+) (ArgumentError)
	from /Library/Ruby/Gems/2.0.0/gems/adp-downloader-0.2.0/lib/adp-downloader.rb:20:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/adp-downloader-0.2.0/lib/adp-downloader.rb:20:in `log_exception_to_file'
	from /Library/Ruby/Gems/2.0.0/gems/adp-downloader-0.2.0/lib/adp-downloader.rb:11:in `rescue in download'
	from /Library/Ruby/Gems/2.0.0/gems/adp-downloader-0.2.0/lib/adp-downloader.rb:6:in `download'
	from /Library/Ruby/Gems/2.0.0/gems/adp-downloader-0.2.0/bin/adp-downloader:5:in `<top (required)>'
	from /usr/local/bin/adp-downloader:23:in `load'
	from /usr/local/bin/adp-downloader:23:in `<main>'

**Comment by andersonvom** [comment]
Interesting. This means you actually got a different error and that logging the error you got failed. I'll submit a fix shortly and you can see what the actual error was.

**Comment by benh57** [comment]
I think the actual error I was getting was 'bad password'. I upgraded to ruby 2.4.0 using brew for myself. :)

-Ben

**Comment by andersonvom** [comment]
Perfect, then! :D
