### ISSUE TITLE
Downloaded pay statements cannot be opened

### ISSUE THREAD

**Issue by rahul-mohan** [andersonvom/adp-downloader#4]
Downloaded paystatement PDFs are not opening. 

On further inspection I think the URLs are not correct anymore. The metadata JSON document has an "/l2" prefixed to the PDF urls. 

      "statementImageUri": {
        "href": "/l2/v1_0/O/A/payStatement/123123123njknk343/images/23223asdasdasd.pdf"
      },

I get the PDF when I try with the /l2 removed.

**Comment by andersonvom** [comment]
Hi @rahul-mohan,

The `/l2` prefix is already being removed from the path in the JSON document as you can see here: https://github.com/andersonvom/adp-downloader/blob/e13b9785dc07348e13ed6d8a41ea7f6f24032357/lib/adp-downloader/statement/statement.rb#L33-L36

Do you think you can run it without `-v` and paste the logs here?

**Comment by andersonvom** [comment]
Closing this for now. Let me know if the problem persists.
